"$schema": https://github.com/hyperledger-labs/fablo/releases/download/1.1.0/schema.json
global:
  fabricVersion: 2.4.2
  tls: true
orgs:
  - organization:
      name: Orderer
      domain: root.com
    orderers:
      - groupName: group1
        prefix: orderer
        type: raft
        instances: 1
  - organization:
      name: Org1
      domain: org1.example.com
    peer:
      instances: 1
  - organization:
      name: Org2
      domain: org2.example.com
    peer:
      instances: 1
  - organization:
      name: Org3
      domain: org3.example.com
    peer:
      instances: 1
  - organization:
      name: Org4
      domain: org4.example.com
    peer:
      instances: 1
  - organization:
      name: Org5
      domain: org5.example.com
    peer:
      instances: 1
  - organization:
      name: Org6
      domain: org6.example.com
    peer:
      instances: 1
  - organization:
      name: Org7
      domain: org7.example.com
    peer:
      instances: 1
  - organization:
      name: Org8
      domain: org8.example.com
    peer:
      instances: 1
  - organization:
      name: Org9
      domain: org9.example.com
    peer:
      instances: 1
  - organization:
      name: Org10
      domain: org10.example.com
    peer:
      instances: 1
channels:
  - name: mychannel
    orgs:
      - name: Org1
        peers:
          - peer0
      - name: Org2
        peers:
          - peer0
      - name: Org3
        peers:
          - peer0
      - name: Org4
        peers:
          - peer0
      - name: Org5
        peers:
          - peer0
      - name: Org6
        peers:
          - peer0
      - name: Org7
        peers:
          - peer0
      - name: Org8
        peers:
          - peer0
      - name: Org9
        peers:
          - peer0
      - name: Org10
        peers:
          - peer0
chaincodes:
  - name: auti-org-chain
    version: 0.1.0
    lang: golang
    channel: mychannel
    init: '{"Args":[]}'
    endorsement: AND('Org1MSP.member', 'Org2MSP.member', 'Org3MSP.member', 'Org4MSP.member', 'Org5MSP.member', 'Org6MSP.member', 'Org7MSP.member', 'Org8MSP.member', 'Org9MSP.member', 'Org10MSP.member')
    directory: "../contract/clolc_org_chain"