"$schema": https://github.com/hyperledger-labs/fablo/releases/download/1.1.0/schema.json
global:
  fabricVersion: 2.4.2
  tls: true
orgs:
  - organization:
      name: Orderer
      domain: root.com
    orderers:
      - groupName: group1
        prefix: orderer
        type: raft
        instances: 1
  - organization:
      name: Org1
      domain: org1.example.com
    peer:
      instances: 1
  - organization:
      name: Aud1
      domain: aud1.example.com
    peer:
      instances: 1
channels:
  - name: mychannel
    orgs:
      - name: Org1
        peers:
          - peer0
      - name: Aud1
        peers:
          - peer0
chaincodes:
  - name: auti-local-chain
    version: 0.1.0
    lang: golang
    channel: mychannel
    init: '{"Args":[]}'
    endorsement: AND('Org1MSP.member', 'Aud1MSP.member')
    directory: "org-global-chaincode"
