"$schema": https://github.com/hyperledger-labs/fablo/releases/download/1.1.0/schema.json
global:
  fabricVersion: 2.4.2
  tls: true
orgs:
  - organization:
      name: Orderer
      domain: root.com
    orderers:
      - groupName: group1
        prefix: orderer
        type: raft
        instances: 1
  - organization:
      name: Aud1
      domain: aud1.example.com
    peer:
      instances: 1
  - organization:
      name: Aud2
      domain: aud2.example.com
    peer:
      instances: 1
  - organization:
      name: Aud3
      domain: aud3.example.com
    peer:
      instances: 1
  - organization:
      name: Aud4
      domain: aud4.example.com
    peer:
      instances: 1
  - organization:
      name: Aud5
      domain: aud5.example.com
    peer:
      instances: 1
  - organization:
      name: Aud6
      domain: aud6.example.com
    peer:
      instances: 1
  - organization:
      name: Aud7
      domain: aud7.example.com
    peer:
      instances: 1
  - organization:
      name: Aud8
      domain: aud8.example.com
    peer:
      instances: 1
  - organization:
      name: Aud9
      domain: aud9.example.com
    peer:
      instances: 1
  - organization:
      name: Aud10
      domain: aud10.example.com
    peer:
      instances: 1
channels:
  - name: mychannel
    orgs:
      - name: Aud1
        peers:
          - peer0
      - name: Aud2
        peers:
          - peer0
      - name: Aud3
        peers:
          - peer0
      - name: Aud4
        peers:
          - peer0
      - name: Aud5
        peers:
          - peer0
      - name: Aud6
        peers:
          - peer0
      - name: Aud7
        peers:
          - peer0
      - name: Aud8
        peers:
          - peer0
      - name: Aud9
        peers:
          - peer0
      - name: Aud10
        peers:
          - peer0
chaincodes:
  - name: auti-aud-chain
    version: 0.1.0
    lang: golang
    channel: mychannel
    init: '{"Args":[]}'
    endorsement: AND('Aud1MSP.member', 'Aud2MSP.member', 'Aud3MSP.member', 'Aud4MSP.member', 'Aud5MSP.member', 'Aud6MSP.member', 'Aud7MSP.member', 'Aud8MSP.member', 'Aud9MSP.member', 'Aud10MSP.member')
    directory: "../contract/clolc_aud_chain"